objects_list:
    default: ["CYLINDER", 0.11 , 0.055]
    sponge: ["CYLINDER", 0.03 , 0.055]
    greentea: ["CYLINDER", 0.21 , 0.055]
    toiletpaper: ["CYLINDER", 0.13 , 0.03]
    papayamilk: ["CYLINDER", 0.13 , 0.025]
    soap: ["CYLINDER", 0.06 , 0.055]
    puremilk: ["CYLINDER", 0.1 , 0.035]
    lotion: ["CYLINDER", 0.12 , 0.055]
    water: ["CYLINDER", 0.23 , 0.055]
    toothpaste: ["CYLINDER", 0.05 , 0.25]
    oragejuice: ["CYLINDER", 0.13 , 0.025]
    cloth: ["CYLINDER", 0.1 , 0.055]
    beer: ["CYLINDER", 0.11 , 0.055]
    biscuits: ["CYLINDER", 0.22 , 0.055]
    coconutcereals: ["CYLINDER", 0.12 , 0.05]
    bubblegum: ["CYLINDER", 0.02 , 0.055]
    chocolates: ["CYLINDER", 0.07 , 0.04]
    cocoballs: ["CYLINDER", 0.23 , 0.055]
    tomatochips: ["CYLINDER", 0.21 , 0.035]
    barbecuechips: ["CYLINDER", 0.21 , 0.035]
    gramsoup: ["CYLINDER", 0.12 , 0.035]
    honeychips: ["CYLINDER", 0.25, 0.09]
    beansauce: ["CYLINDER", 0.11 , 0.035]
    pear: ["CYLINDER", 0.07 , 0.03]
    lemon: ["CYLINDER", 0.08 , 0.03]
    apple: ["CYLINDER", 0.07 , 0.03]
    bowl: ["CYLINDER", 0.07 , 0.055]
    eggstars: ["CYLINDER", 0.22 , 0.06]
    fanta: ["CYLINDER", 0.11 , 0.055]
    coffee: ["CYLINDER", 0.11 , 0.055]