# Generado con script desde configuracion de motores Dynamixel
l_shoulder_pitch_controller:
  controller:
    module: joint_position_mx_controller
    package: bender_arm
    type: JointPositionMXController
  joint_name: l_shoulder_pitch_joint
  joint_speed: 1.0
  p_gain: 15
  i_gain: 5
  d_gain: 0
  joint_torque_limit: 1.0
  torque_enable_init: False
  motor:
    id: 1
    init: 2055
    max: 785
    min: 3055

l_shoulder_roll_controller:
  controller:
    module: joint_position_mx_controller
    package: bender_arm
    type: JointPositionMXController
  joint_name: l_shoulder_roll_joint
  joint_speed: 1.0
  p_gain: 15
  i_gain: 5
  d_gain: 0
  joint_torque_limit: 1.0
  torque_enable_init: False
  motor:
    id: 2
    init: 2590
    max: 1605
    min: 2745

l_shoulder_yaw_controller:
  controller:
    module: joint_position_controller
    package: bender_arm
    type: JointPositionController
  joint_name: l_shoulder_yaw_joint
  joint_speed: 1.0
  joint_compliance_slope: 64
  joint_compliance_margin: 0
  joint_compliance_punch: 0
  joint_torque_limit: 1.0
  torque_enable_init: False
  enable_pid: True
  p_gain: 0.8
  i_gain: 0.5 
  d_gain: 0.0
  i_clamp: 1.0
  motor:
    id: 3
    init: 435
    max: 165
    min: 725

l_elbow_pitch_controller:
  controller:
    module: joint_position_mx_controller
    package: bender_arm
    type: JointPositionMXController
  joint_name: l_elbow_pitch_joint
  joint_speed: 1.0
  p_gain: 15
  i_gain: 5
  d_gain: 0
  joint_torque_limit: 1.0
  torque_enable_init: False
  motor:
    id: 4
    init: 2080
    max: 3280
    min: 1400

l_elbow_yaw_controller:
  controller:
    module: joint_position_controller
    package: bender_arm
    type: JointPositionController
  joint_name: l_elbow_yaw_joint
  joint_speed: 1.0
  joint_compliance_slope: 32
  joint_compliance_margin: 0
  joint_compliance_punch: 0
  joint_torque_limit: 1.0
  torque_enable_init: False
  enable_pid: True
  p_gain: 0.8
  i_gain: 0.5 
  d_gain: 0.0
  i_clamp: 1.0
  motor:
    id: 5
    init: 430
    max: 195
    min: 645

l_wrist_pitch_controller:
  controller:
    module: joint_position_controller
    package: bender_arm
    type: JointPositionController
  joint_name: l_wrist_pitch_joint
  joint_speed: 1.0
  joint_compliance_slope: 32
  joint_compliance_margin: 0
  joint_compliance_punch: 0
  joint_torque_limit: 1.0
  torque_enable_init: False
  enable_pid: True
  p_gain: 0.8
  i_gain: 0.5 
  d_gain: 0.0
  i_clamp: 2.0
  motor:
    id: 6
    init: 340
    max: 110
    min: 560