# Generado con script desde configuracion de motores Dynamixel

r_shoulder_pitch_controller:
  controller:
    module: joint_position_mx_controller
    package: bender_arm
    type: JointPositionMXController
  joint_name: r_shoulder_pitch_joint
  joint_speed: 1.0
  p_gain: 15
  i_gain: 5
  d_gain: 0
  joint_torque_limit: 1.0
  torque_enable_init: False
  motor:
    id: 11
    init: 2035
    max: 3325
    min: 1055

r_shoulder_roll_controller:
  controller:
    module: joint_position_controller
    package: bender_arm
    type: JointPositionController
  joint_name: r_shoulder_roll_joint
  joint_speed: 1.0
  joint_compliance_slope: 64
  joint_compliance_margin: 0
  joint_compliance_punch: 0
  joint_torque_limit: 1.0
  torque_enable_init: False
  enable_pid: True
  p_gain: 0.8
  i_gain: 0.5 
  d_gain: 0.0
  i_clamp: 1.0
  motor:
    id: 12
    init: 2090
    max: 3505
    min: 1866

r_shoulder_yaw_controller:
  controller:
    module: joint_position_controller
    package: bender_arm
    type: JointPositionController
  joint_name: r_shoulder_yaw_joint
  joint_speed: 1.0
  joint_compliance_slope: 32
  joint_compliance_margin: 0
  joint_compliance_punch: 0
  joint_torque_limit: 1.0
  torque_enable_init: False
  enable_pid: True
  p_gain: 0.8
  i_gain: 0.5 
  d_gain: 0.0
  i_clamp: 1.0
  motor:
    id: 13
    init: 310
    max: 40
    min: 600

r_elbow_pitch_controller:
  controller:
    module: joint_position_mx_controller
    package: bender_arm
    type: JointPositionMXController
  joint_name: r_elbow_pitch_joint
  joint_speed: 1.0
  p_gain: 15
  i_gain: 5
  d_gain: 0
  joint_torque_limit: 1.0
  torque_enable_init: False
  motor:
    id: 14
    init: 2100
    max: 3245
    min: 1405

r_elbow_yaw_controller:
  controller:
    module: joint_position_controller
    package: bender_arm
    type: JointPositionController
  joint_name: r_elbow_yaw_joint
  joint_speed: 1.0
  joint_compliance_slope: 32
  joint_compliance_margin: 0
  joint_compliance_punch: 0
  joint_torque_limit: 1.0
  torque_enable_init: False
  enable_pid: True
  p_gain: 0.8
  i_gain: 0.5 
  d_gain: 0.0
  i_clamp: 1.0
  motor:
    id: 15
    init: 590
    max: 825
    min: 375

r_wrist_pitch_controller:
  controller:
    module: joint_position_controller
    package: bender_arm
    type: JointPositionController
  joint_name: r_wrist_pitch_joint
  joint_speed: 1.0
  joint_compliance_slope: 32
  joint_compliance_margin: 0
  joint_compliance_punch: 0
  joint_torque_limit: 1.0
  torque_enable_init: False
  enable_pid: True
  p_gain: 0.8
  i_gain: 0.5 
  d_gain: 0.0
  i_clamp: 2.0
  motor:
    id: 16
    init: 599
    max: 345
    min: 795